sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kf58f6DIPxv0PQqYx/KtloMYxMfC5Lp/6EDXWu2I1tGmMJ2tZoYV1zqjpppC+Hm9cnelo53a6lrV3E1Aih6Gzwy6lIujGleciMUyietQDMbR/yvq7VC/W2F+QPgA4dnsQdutcXQ3syo32vNfWVGfDm7fKDICkxiPKdsggAXUBHnE2bGoJ4ROrIPNRC0+CkKL7xo2Wmf32J6prhMj8WA72bKo3NJmi7pFB6OZfHzhMXyf+NcU5y68rqsSga9hfkMZcnpKCFfs2+JEmuetiijA2yTebyDKJehEcVWgRo1emGEJk4lxIGZB6Z9NS5p6hjnVhlg90QxJgWQgEw0bW0W8PnbFQh88RzlZUP2JB5ECW7KvPI0+DWeg5Ia0gFDC1tAgEKINd4b8Swc+y0mMLH65QNJHDLsqKyiSzXfm/b0MpxvZbbcg484cDmorEL5eFfzLZi/O2zE8jhk0w6AU0bGtTClZzLKNC3hU+GCoYsVO1MYsQ3LkBY97zKdHX3xtDpPElugstG6fYbZj6Hd7Q1Hh7c4m8kWVSiLFehAWmZA7Fl3FaOajaTQl59DWcNyX6Z4c7tGPM3b1vzwprsQ+Vq58Nm67WLkJO1EARk5O1b1IOp6piTu6482a7bW7541Tu/mM/lvjunnAy59l5Da8WnwjhEK8FMLHoeLdVUPXIhkwfdI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Chopin---the-Man-and-His-Music_4939
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy